export const T = {
  cz: {
    homeTitle: 'Teplo vytvořené spalováním v kotli přeměňuje vodu na páru.',
    homeBody: 'Otevři ventil a pusť páru do turbíny.',
    stepMsg: 'Tlak páry je příliš nízký.',
    doneMsg: 'Ventil je plně otevřen, pára proudí do turbíny.',
    turbineMsg: 'Pára pohání lopatky rotoru turbíny. Ten je připojen ke generátoru, který elektromagnetickou indukcí vyrábí elektřinu.',
    turbineSubMsg: 'Pro odeslání vyrobené elektřiny stiskněte tlačítko {BLESK}.'
  },

  en: {
    homeTitle: 'The heat generated by combustion in the boiler converts water into steam.',
    homeBody: 'Open the valve and release steam into the turbine.',
    stepMsg: 'The steam pressure is too low.',
    doneMsg: 'The valve is fully open, steam flows into the turbine.',
    turbineMsg: 'The steam drives the turbine rotor blades. The turbine rotor is connected to the generator rotor that produces electricity by electromagnetic induction.',
    turbineSubMsg: 'To provide the electricity produced, press the {BLESK} button.',
  },
  
  de: {
    homeTitle: 'Die beim Verbrennen erzeugte Wärme wandelt Wasser im Kessel in Dampf um.',
    homeBody: 'Öffne das Ventil und leite den Dampf in die Turbine.',
    stepMsg: 'Der Dampfdruck ist zu niedrig.',
    doneMsg: 'Das Ventil ist vollständig geöffnet, der Dampf strömt in die Turbine.',
    turbineMsg: 'Der Dampf treibt die Schaufeln des Turbinenrotors an. Dieser ist mit dem Rotor des Generators verbunden, der durch elektromagnetische Induktion Strom erzeugt. ',
    turbineSubMsg: 'Um die erzeugte Elektrizität bereitzustellen, drücken Sie die {BLESK}-Taste.',
  },
};
