import { useState, useEffect, useRef, useCallback } from 'react';

const WS_URL = 'ws://localhost:8765';

const T = {
  cz: {
    title: 'Teplo vytvořené spalováním v kotli přeměňuje vodu na páru.',
    body: 'Pára, která prošla parní turbínou je ochlazena v kondenzátoru na kapalnou vodu. Chladící okruh doplňuje chladící věž. Voda z okruhu je v kotli opět ohřátá a přeměněná na páru.',
  },
  en: {
    title: 'The heat generated by combustion in the boiler converts water into steam.',
    body: 'The steam that has passed through the steam turbine is cooled into liquid water in a condenser. A cooling tower completes the cooling circuit. The water from the circuit is reheated and converted to steam in the boiler.',
  },
  de: {
    title: 'Die beim Verbrennen erzeugte Wärme wandelt Wasser im Kessel in Dampf um.',
    body: 'Der Dampf, der die Turbine durchströmt hat, wird im Kondensator wieder zu Wasser abgekühlt. Der Kühlkreislauf wird durch den Kühlturm unterstützt. Das Wasser wird im Kessel erneut erhitzt und wieder in Dampf umgewandelt.',
  },
};

export default function App() {
  const [screen, setScreen] = useState('sleep'); // sleep | active
  const [language, setLanguage] = useState('cz');
  const ws = useRef(null);
  const wsTimer = useRef(null);

  const handleMessage = useCallback((msg) => {
    if (msg.type !== 'trigger') return;
    if (msg.device === 'BUTTON' && msg.value?.pressed) {
      if (msg.id === 'LANG_CZ') setLanguage('cz');
      if (msg.id === 'LANG_EN') setLanguage('en');
      if (msg.id === 'LANG_DE') setLanguage('de');
      if (msg.id === 'PHASE3_START') setScreen('active');
      if (msg.id === 'SLEEP_ALL' || msg.id === 'RESET_ALL') setScreen('sleep');
    }
  }, []);

  const connect = useCallback(() => {
    const socket = new WebSocket(WS_URL);
    socket.onopen = () => console.log('WS connected');
    socket.onmessage = (e) => { try { handleMessage(JSON.parse(e.data)); } catch {} };
    socket.onclose = () => {
      clearTimeout(wsTimer.current);
      wsTimer.current = setTimeout(connect, 2000);
    };
    ws.current = socket;
  }, [handleMessage]);

  useEffect(() => {
    connect();
    return () => { ws.current?.close(); clearTimeout(wsTimer.current); };
  }, [connect]);

  // ── KEYBOARD SIMULATOR ────────────────────────────────
  useEffect(() => {
    const onKey = (e) => {
      switch (e.key) {
        case ' ': case 'Enter': case 'p': case 'P':
          e.preventDefault();
          handleMessage({ type:'trigger', device:'BUTTON', id:'PHASE3_START', value:{ pressed: true } });
          break;
        case 'r': case 'R': case 'Escape':
          handleMessage({ type:'trigger', device:'BUTTON', id:'RESET_ALL', value:{ pressed: true } });
          break;
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [handleMessage]);

  const lang = T[language];

  if (screen === 'sleep') {
    return (
      <div className="screen sleep">
        <img src="/g/chladici_vez_sporic-02.png" alt="" className="sleep-img" />
      </div>
    );
  }

  return (
    <div className="screen active">
      <div className="text-panel">
        <h1 className="panel-title">{lang.title}</h1>
        <p className="panel-body">{lang.body}</p>
      </div>
      <div className="diagram-area">
        <img src="/g/chladici_vez_koty_oprava-01.png" alt="Cooling circuit" className="diagram-img" />
      </div>
    </div>
  );
}
